environment:
  matrix:

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"
      py_minor: "7"

    # Also test a Python version not pre-installed
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10

    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"
      py_minor: "6"

    - PYTHON: "C:\\Python254"
      PYTHON_VERSION: "2.5.4"
      PYTHON_ARCH: "32"
      py_minor: "5"

    - PYTHON: "C:\\Python244"
      PYTHON_VERSION: "2.4.4"
      PYTHON_ARCH: "32"
      py_minor: "4"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe -c \"import sys; print(sys.version)"
  - "%PYTHON%\\python.exe -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "%PYTHON%\\python.exe -m pip install nose"
  - "%PYTHON%\\python.exe -m pip install argparse"

# Not a C# project, build stuff at the test step instead.
build: false

test_script:
  # run the project tests
  - "nosetests test_png.py"

after_test:
  # If tests are successful, update coverage.
  - "SET CI_BRANCH=%APPVEYOR_REPO_BRANCH%"
  - "SET COVERALLS_PARALLEL=true"
  - "SET COVERALLS_REPO_TOKEN=w8NKB65QmekU0thmQV1E5yEaFpYIyUAYP"
  #- "if %py_minor% GEQ 6 %CMD_IN_ENV% coveralls"

#notifications:
#  - provider: Webhook
#    url: https://coveralls.io/webhook?repo_token=w8NKB65QmekU0thmQV1E5yEaFpYIyUAYP
#    method: GET
#artifacts:
#  # Archive the generated wheel package in the ci.appveyor.com build report.
#  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
